#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port4,           rightDrive1,   tmotorNone, openLoop)
#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port6,           neckMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           twistyMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightDrive,    tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)
//Excluded basedon VEXnet Upgrade.  Required for 75 MHz crystals.  Ten second buffer added for each timing
//#pragma autonomousDuration(25)
//#pragma userControlDuration(115)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	//wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	//// Move forward at full power for 3 seconds
	//motor[rightDrive] = 127;		  // Motor on port2 is run at full (127) power forward
	//motor[leftDrive]  = 127;		  // Motor on port3 is run at full (127) power forward
	//wait1Msec(2000);             // Robot runs previous code for 1000 milliseconds before moving on
	//motor[rightDrive] = 127;		//robot turns right .5 sec
	//motor[leftDrive] = -127;
	//wait1Msec(500);
	//motor[rightDrive] = 127;		//robot moves forward for 2 seconds
	//motor[leftDrive] = 127;
	//wait1Msec(2000);

	motor[rightDrive] = -50;
	motor[leftDrive] =  50;
	wait1Msec(500);
	motor[rightDrive]  = 127;
	motor[leftDrive] = 127;
	wait1Msec(1500);
	motor[rightDrive] = 127;
	motor[leftDrive] = -127;
	wait1Msec(500);
	motor[rightDrive] = 127;
	motor[leftDrive] = 127;
	wait1Msec(1500);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	//Infinite Loop
	while(1 == 1)
	{
		// Attaches right and left drive to left/right vertical joysticks on primary controller
		motor[rightDrive] = vexRT[Ch3];
		motor[leftDrive]  = vexRT[Ch2];

		// Attaches twisty motor (allows horizontal movement of the claw) to the right horizontal joystick on the partner controller
		motor[twistyMotor] = vexRT[Ch1Xmtr2];

		// Attaches arm motor (vertical movement of claw) to the right vertical joystick of the partner controller
		//motor[armMotor] = vexRT[Ch2Xmtr2];
		//		if(vexRT[Btn5UXmtr2] == 1)
		//			motor[armMotor] = 99;
		//		}
		//		else if(vexRT[Btn5DXmtr2] == 1) {
		//			motor[armMotor] = -99;
		//		}
		//		else {
		//			motor[armMotor] = 0;
		//		}
		motor[clawMotor] = vexRT[Ch4];


		// Attatches claw motor to the right up/down buttons on the partner controller
		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[clawMotor] = 127;
		}
		else if(vexRT[Btn6DXmtr2] == 1)
		{
			motor[clawMotor] = -127;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
}
