#pragma config(Motor,  port1,           skizzorMotor,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	// Left and right drive motors - hooked up via Y-connector
	motor[rightDrive] = vexRT[Ch3];
	motor[leftDrive]  = vexRT[Ch2];

	// Controls for the scissor lift
	if(vexRT[Btn6U]){
		motor[skizzorMotor] = 127;
	}
	else if(vexRT[Btn6D]) {
		motor[skizzorMotor] = -127;
	}
	else {
		motor[skizzorMotor] = 0;
	}

}
