#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           twistyMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           notWorking,    tmotorNone, openLoop)
#pragma config(Motor,  port6,           notWorking,    tmotorNone, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Dual Joystick Control with 4 Motors -                               *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing both right-side motors (ports 2 and 3) in the "Motors and Sensors Setup" is       *|
|*        needed with the "VEX Tumbler" model, but may not be needed for all robot configurations.    *|
|*    2)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    3)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]                [Type]                [Description]                   *|
|*    Motor Port 2        frontRightMotor       VEX 3-wire module     Right side motor                *|
|*    Motor Port 3        backRightMotor        VEX 3-wire module     Right side motor                *|
|*    Motor Port 4        frontLefttMotor       VEX 3-wire module     Left side motor                 *|
|*    Motor Port 5        backLeftMotor         VEX 3-wire module     Left side motor                 *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  while(1 == 1)
  {
  	// Attaches right and left drive to left/right vertical joysticks on primary controller
    motor[rightDrive] = vexRT[Ch3];
    motor[leftDrive]  = vexRT[Ch2];
    tankControl(vexRT[Ch2],vexRT[Ch3], 127);

    // Attaches twisty motor (allows horizontal movement of the claw) to the right horizontal joystick on the partner controller
   	motor[twistyMotor] = vexRT[Ch1Xmtr2];

   	// Attaches arm motor (vertical movement of claw) to the right vertical joystick of the partner controller
    //motor[armMotor] = vexRT[Ch2Xmtr2];
    if(vexRT[Btn5UXmtr2] == 1)
    {
    	motor[armMotor] = 99;
    }
    else if(vexRT[Btn5DXmtr2] == 1) {
    	motor[armMotor] = -99;
    }
    else {
    	motor[armMotor] = 0;
    }

    // Attatches claw motor to the right up/down buttons on the partner controller
    if(vexRT[Btn6UXmtr2] == 1)
    {
      motor[clawMotor] = 127;
    }
    else if(vexRT[Btn6DXmtr2] == 1)
    {
      motor[clawMotor] = -127;
    }
    else
    {
      motor[clawMotor] = 0;
    }
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
