#pragma config(Motor,  port3,           bothClaws,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bothDoors,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftArm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftLiftArm,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"

// lol pre auton stuff
void pre_auton(){
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

// AUTONOMOUS CONTROL
task autonomous()
{
	// Move forward at full power for 4 seconds
	motor[leftDrive] = 127;		  // Motor on port2 is run at full (127) power forward
	motor[rightDrive]  = 127;		  // Motor on port3 is run at full (127) power forward
	delay(5000);	            // Robot runs previous code for 3000 milliseconds before moving on'
	motor[rightDrive] = 0; 			// Backup force stop - just in case
	motor[leftDrive] = 0;
}												            // Program ends, and the robot stops


// DRIVING CONTROL
task usercontrol()
{

	//Infinite Loop
	while(1 == 1)
	{

		//Drive Control via Tank Control
		//Right motors are paired [rightDrive]
		//Left motors are paired [leftDrive]
		motor[rightDrive] = vexRT[Ch2];
		motor[leftDrive] = vexRT[Ch3];
		tankControl(vexRT[Ch2],vexRT[Ch3], 127);

		//Lift Control
		//Outside left is paired with inside right [leftLiftArm]
		//Outside right is paired with inside left [rightLiftArm]

		//Joystick Control
		motor[leftLiftArm] = vexRT[Ch2Xmtr2];
		motor[rightLiftArm] = vexRT[Ch2Xmtr2];
		tankControl(vexRT[Ch2Xmtr2],vexRT[Ch2Xmtr2], 127);

		/*
		//Button Control
		if(vexRT[Btn6UXmtr2] == 1)
		{
		motor[leftLiftArm] = 127;
		motor[rightLiftArm] = 127;
		}
		else if(vexRT[Btn5UXmtr2] == 1)
		{
		motor[leftLiftArm] = -127;
		motor[rightLiftArm] = -127;
		}
		else
		{
		motor[leftLiftArm] = 0;
		motor[rightLiftArm] = 0;
		}
		*/

		//Door Control
		//Both doors wired together with one wiring flipped for reversal [bothDoors]
		if(vexRT[Btn6U] == 1)
		{
			motor[bothDoors] = 127;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[bothDoors] = -127;
		}
		else
		{
			motor[bothDoors] = 0;
		}

		//Claw Control
		//Both claws wired together with one wiring flipped for reversal [bothClaws]
		if(vexRT[Btn6UXmtr2] == 1)
		{
			motor[bothClaws] = 127;
		}
		else if(vexRT[Btn5UXmtr2] == 1)
		{
			motor[bothClaws] = -127;
		}
		else
		{
			motor[bothClaws] = 0;
		}
	}
}
