#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
			/* drive & turn */
			setMotorSpeed(leftMotor, 127);
			setMotorSpeed(rightMotor, 127);
			/* catapult ONCE */
			/*setMotorSpeed(cataMotor, 127);*/
			//SETmOTORSPEED EAT ERIC
			wait1Msec(20000);
	}


