#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* dank memes */

/* to download some more RAM, visit downloadmoreram.com it is legit */
/*"Chromebooks don't have hard drives."*/

/* REMEMBER TO DOWNLOAD MORE RAM */

/* DOWNLOAD MOARRRR RAMMMM */


/*Eric's note to self: Warframe*/

task main()
{
			/* drive & turn */
			setMotorSpeed(leftMotor, 127);
			setMotorSpeed(rightMotor, 127);
			/* catapult ONCE */
			/*setMotorSpeed(cataMotor, 127);*/
			//SETmOTORSPEED EAT ERIC
			wait1Msec(20000);
			// DAD = TRIGGERED
			// note: SOFTWARE CONTAIN IS VERY HIGH
	}


/* Special Note: Don't pay David */
