#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* dank memes */

/* to download some more RAM, visit downloadmoreram.com it is legit */
/*"Chromebooks don't have hard drives."*/

/* REMEMBER TO DOWNLOAD MORE RAM */

/* DOWNLOAD MOARRRR RAMMMM */

task main()
{
	while(true == true){
		if(vexRT[Btn6U]){
			/* drive & turn */
			setMotorSpeed(leftMotor, 127);
			setMotorSpeed(rightMotor, 127);
			wait1Msec(5000);
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(rightMotor, 127);
			wait1Msec(2000);
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);

			/* catapult ONCE */
			/*setMotorSpeed(cataMotor, 127);*/
			//SETmOTORSPEED EAT ERIC


		}
	}
}


/* Special Note: Don't pay David */
