#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Motor,  port3,           bothClaws,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bothDoors,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftArm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftLiftArm,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)
//Excluded basedon VEXnet Upgrade.  Required for 75 MHz crystals.  Ten second buffer added for each timing
//#pragma autonomousDuration(25)
//#pragma userControlDuration(115)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	//Autonomous move forward for 5 second
	motor[rightDrive] = 127;
	motor[leftDrive] = 127;
	delay(5000);
  motor[rightDrive] = 0;
	motor[leftDrive] = 0;

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	//Infinite Loop
  while(1 == 1)
  {

  	//DRIVE CONTROL VIA TANK CONTROL
    //Right motors are paired [rightDrive]
    //Left motors are paired [leftDrive]
  	motor[rightDrive] = vexRT[Ch2];
		motor[leftDrive] = vexRT[Ch3];
		tankControl(vexRT[Ch2],vexRT[Ch3], 127);

    //LIFT CONTROL WITH LIMIT SWITCH
		//Outside left is paired with inside right [leftLiftArm]
  	//Outside right is paired with inside left [rightLiftArm]
		if(SensorValue(limitSwitch) == 0)
		{
			motor[leftLiftArm] = vexRT[Ch2Xmtr2];
    	motor[rightLiftArm] = vexRT[Ch2Xmtr2];
			tankControl(vexRT[Ch2Xmtr2],vexRT[Ch2Xmtr2], 127);

			if(SensorValue(limitSwitch) == 1)
			{
				wait1Msec(250);
				while(SensorValue(limitSwitch) == 1)
				{
					motor[leftLiftArm] = -127/4;
					motor[rightLiftArm] = -127/4;
				}
			}
		}

    //DOOR CONTROL
    //Both doors wired together with one wiring flipped for reversal [bothDoors]
    if(vexRT[Btn6U] == 1)
    {
      motor[bothDoors] = 127;
    }
    else if(vexRT[Btn5U] == 1)
    {
      motor[bothDoors] = -127;
    }
    else
    {
      motor[bothDoors] = 0;
    }

    //CLAW CONTROL
    //Both claws wired together with one wiring flipped for reversal [bothClaws]
    if(vexRT[Btn6UXmtr2] == 1)
    {
      motor[bothClaws] = 127;
    }
    else if(vexRT[Btn5UXmtr2] == 1)
    {
      motor[bothClaws] = -127;
    }
    else
    {
      motor[bothClaws] = 0;
    }
  }
}
