#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Motor,  port3,           bothClaws,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bothDoors,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftArm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftLiftArm,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Infinite Loop
	while(1 == 1)
	{

		//Autonomous move forward for 5 second
		motor[rightDrive] = 127;
		motor[leftDrive] = 127;
		wait1Msec(5000);
  	motor[rightDrive] = 0;
		motor[leftDrive] = 0;
	}
}
