#pragma config(Motor,  port3,           bothClaws,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           bothDoors,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftArm,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftLiftArm,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	//Infinite Loop
  while(1 == 1)
  {

  	//DRIVE CONTROL VIA TANK CONTROL
    //Right motors are paired [rightDrive]
    //Left motors are paired [leftDrive]
  	motor[rightDrive] = vexRT[Ch2];
		motor[leftDrive] = vexRT[Ch3];
		tankControl(vexRT[Ch2],vexRT[Ch3], 127);

    //LIFT CONTROL
		//Outside left is paired with inside right [leftLiftArm]
  	//Outside right is paired with inside left [rightLiftArm]

		motor[leftLiftArm] = vexRT[Ch2Xmtr2];
    motor[rightLiftArm] = vexRT[Ch2Xmtr2];
		tankControl(vexRT[Ch2Xmtr2],vexRT[Ch2Xmtr2], 127);

    //DOOR CONTROL
    //Both doors wired together with one wiring flipped for reversal [bothDoors]
    if(vexRT[Btn6U] == 1)
    {
      motor[bothDoors] = 127;
    }
    else if(vexRT[Btn5U] == 1)
    {
      motor[bothDoors] = -127;
    }
    else
    {
      motor[bothDoors] = 0;
    }

    //CLAW CONTROL
    //Both claws wired together with one wiring flipped for reversal [bothClaws]
    if(vexRT[Btn6UXmtr2] == 1)
    {
      motor[bothClaws] = 127;
    }
    else if(vexRT[Btn5UXmtr2] == 1)
    {
      motor[bothClaws] = -127;
    }
    else
    {
      motor[bothClaws] = 0;
    }
  }

}
